project:
  type: book
  output-dir: docs

book:
  title: "Data Science - Global Plant Health MSc Course"
  author: "Dan MacLean"
  date: last-modified
  date-format: "MMMM, YYYY"
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - flippedclass.qmd
    - howtosucceed.qmd
    - part: topics.qmd
      chapters:
        - genomics.qmd
        - dataviz.qmd
        - stats.qmd
        - nonfreq.qmd
        - ml.qmd
        - python.qmd
        - literacy.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

comments:
  hypothesis: true

